export const STATUS = {
  NEEDED: "GOAT_PURCHASE_NEEDED",
  IN_PROGRESS: "GOAT_PURCHASE_IN_PROGRESS",
  PURCHASED: "GOAT_PURCHASED",
  FAILED: "GOAT_PURCHASE_FAILED",
  NO_PRICE: "GOAT_NO_VALID_PRICE",
  SIZE_NOT_FOUND: "GOAT_SIZE_NOT_FOUND",
  PRODUCT_NOT_FOUND: "GOAT_PRODUCT_NOT_FOUND",
  ADDRESS_MISMATCH: "GOAT_ADDRESS_MISMATCH",
  PAYMENT_MISMATCH: "GOAT_PAYMENT_MISMATCH"
};
