export const STATUS = {
  IN_PROGRESS: "PURCHASE_IN_PROGRESS",
  PURCHASED: "PURCHASED",
  FAILED: "PURCHASE_FAILED",
  NO_VALID_PRICE: "NO_VALID_PRICE",
  SIZE_NOT_FOUND: "SIZE_NOT_FOUND",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  ADDRESS_MISMATCH: "ADDRESS_MISMATCH",
  PAYMENT_MISMATCH: "PAYMENT_MISMATCH"
};
